Repository artefactual/archivematica-storage-service, pull requests merged in 2018-03, with the labels that each got.

#335 Provides lowercase checking of API reingest type
  storage_service/locations/models/package.py
Labels: enhancement

#320 Reduce number of copies by introducing space.move_direct
  storage_service/locations/api/resources.py
  storage_service/locations/models/local_filesystem.py
  storage_service/locations/models/nfs.py
  storage_service/locations/models/package.py
  storage_service/locations/models/space.py
Labels: CUL: phase 2, Columbia University Library

#316 Add mariadb-devel dependency
  osdeps/CentOS-7.json
  osdeps/RedHat-7.json
Labels: CUL: phase 2, Columbia University Library, In Progress
